name: test-cicd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.X

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CICD_TOKEN }}
          BRANCH: gh-pages
          publish_dir: ./dist
